---

apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app: myweb


spec:
  ports:
  - port: 80
    protocol: TCP
  clusterIP: None
  selector:
    app: myweb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:

    matchLabels:
      app: myweb
  serviceName: "service1"
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - image: yamikarajputd/capstone:1.01
          imagePullPolicy: IfNotPresent
          name: myweb




