---
apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: myweb
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30000
    protocol: TCP
  selector:
    app: capstone



