---
apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: myweb
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30000
    protocol: TCP
  selector:
    app: capstone

---
apiVersion: v1
kind: Service
metadata:
  name: sql
  labels:
    app: myweb


spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: sql
